spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/h4to5?autoReconnect=true&useSSL=false
    username: app
    password: app

spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    ddlAuto: update
  show-sql: true